server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xk?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: star
    password: 5H5i9*jj%aGff3
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    open-in-view: true
    show-sql: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zfz.coursemanage.entity
